ALTER TABLE "SurveillanceBlueprint" ADD CONSTRAINT "sr02_fk_001" FOREIGN KEY ("activeVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceBlueprintVersion" ADD CONSTRAINT "sr02_fk_002" FOREIGN KEY ("blueprintId") REFERENCES "SurveillanceBlueprint"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceApplicabilityProfile" ADD CONSTRAINT "sr02_fk_003" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceSceneVariant" ADD CONSTRAINT "sr02_fk_004" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceReviewerPolicy" ADD CONSTRAINT "sr02_fk_005" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCriterion" ADD CONSTRAINT "sr02_fk_006" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCriterion" ADD CONSTRAINT "sr02_fk_007" FOREIGN KEY ("reviewerPolicyId") REFERENCES "SurveillanceReviewerPolicy"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceExpectedStateRule" ADD CONSTRAINT "sr02_fk_008" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceRequirement" ADD CONSTRAINT "sr02_fk_009" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCaptureStep" ADD CONSTRAINT "sr02_fk_010" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceAuthorityBinding" ADD CONSTRAINT "sr02_fk_011" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceOrganizationRuleBinding" ADD CONSTRAINT "sr02_fk_012" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendIdentity" ADD CONSTRAINT "sr02_fk_013" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceSceneInstance" ADD CONSTRAINT "sr02_fk_014" FOREIGN KEY ("roundId") REFERENCES "SurveillanceRound"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceSceneInstance" ADD CONSTRAINT "sr02_fk_015" FOREIGN KEY ("blueprintVersionId") REFERENCES "SurveillanceBlueprintVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceSceneInstance" ADD CONSTRAINT "sr02_fk_016" FOREIGN KEY ("sceneVariantId") REFERENCES "SurveillanceSceneVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceApplicabilityResolution" ADD CONSTRAINT "sr02_fk_017" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceApplicabilityResolution" ADD CONSTRAINT "sr02_fk_018" FOREIGN KEY ("applicabilityProfileId") REFERENCES "SurveillanceApplicabilityProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCriterionRuntime" ADD CONSTRAINT "sr02_fk_019" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCriterionRuntime" ADD CONSTRAINT "sr02_fk_020" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceRequest" ADD CONSTRAINT "sr02_fk_021" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceRequest" ADD CONSTRAINT "sr02_fk_022" FOREIGN KEY ("criterionRuntimeId") REFERENCES "SurveillanceCriterionRuntime"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceRequest" ADD CONSTRAINT "sr02_fk_023" FOREIGN KEY ("evidenceRequirementId") REFERENCES "SurveillanceEvidenceRequirement"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceArtifact" ADD CONSTRAINT "sr02_fk_024" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceArtifact" ADD CONSTRAINT "sr02_fk_025" FOREIGN KEY ("evidenceRequestId") REFERENCES "SurveillanceEvidenceRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceDerivation" ADD CONSTRAINT "sr02_fk_026" FOREIGN KEY ("parentEvidenceId") REFERENCES "SurveillanceEvidenceArtifact"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceDerivation" ADD CONSTRAINT "sr02_fk_027" FOREIGN KEY ("derivedEvidenceId") REFERENCES "SurveillanceEvidenceArtifact"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceObservation" ADD CONSTRAINT "sr02_fk_028" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceObservation" ADD CONSTRAINT "sr02_fk_029" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceInterpretationDescriptor" ADD CONSTRAINT "sr02_fk_030" FOREIGN KEY ("observationId") REFERENCES "SurveillanceObservation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceAssessment" ADD CONSTRAINT "sr02_fk_031" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceEvidenceAssessment" ADD CONSTRAINT "sr02_fk_032" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCandidateVariance" ADD CONSTRAINT "sr02_fk_033" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCandidateVariance" ADD CONSTRAINT "sr02_fk_034" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCandidateVariance" ADD CONSTRAINT "sr02_fk_035" FOREIGN KEY ("observationId") REFERENCES "SurveillanceObservation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCandidateVariance" ADD CONSTRAINT "sr02_fk_036" FOREIGN KEY ("evidenceAssessmentId") REFERENCES "SurveillanceEvidenceAssessment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceReviewPacket" ADD CONSTRAINT "sr02_fk_037" FOREIGN KEY ("candidateVarianceId") REFERENCES "SurveillanceCandidateVariance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceDecisionRecord" ADD CONSTRAINT "sr02_fk_038" FOREIGN KEY ("reviewPacketId") REFERENCES "SurveillanceReviewPacket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceDecisionRecord" ADD CONSTRAINT "sr02_fk_039" FOREIGN KEY ("candidateVarianceId") REFERENCES "SurveillanceCandidateVariance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceDecisionRecord" ADD CONSTRAINT "sr02_fk_040" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceReviewedFinding" ADD CONSTRAINT "sr02_fk_041" FOREIGN KEY ("candidateVarianceId") REFERENCES "SurveillanceCandidateVariance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceReviewedFinding" ADD CONSTRAINT "sr02_fk_042" FOREIGN KEY ("reviewPacketId") REFERENCES "SurveillanceReviewPacket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceFindingVersion" ADD CONSTRAINT "sr02_fk_043" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceFindingCitation" ADD CONSTRAINT "sr02_fk_044" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceFindingCitation" ADD CONSTRAINT "sr02_fk_045" FOREIGN KEY ("findingVersionId") REFERENCES "SurveillanceFindingVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceFindingCitation" ADD CONSTRAINT "sr02_fk_046" FOREIGN KEY ("authorityBindingId") REFERENCES "SurveillanceAuthorityBinding"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceFindingCitation" ADD CONSTRAINT "sr02_fk_047" FOREIGN KEY ("approvalDecisionId") REFERENCES "SurveillanceDecisionRecord"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceImmediateCorrection" ADD CONSTRAINT "sr02_fk_048" FOREIGN KEY ("candidateVarianceId") REFERENCES "SurveillanceCandidateVariance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceImmediateCorrection" ADD CONSTRAINT "sr02_fk_049" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceCorrectiveAction" ADD CONSTRAINT "sr02_fk_050" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceActionEvidence" ADD CONSTRAINT "sr02_fk_051" FOREIGN KEY ("actionId") REFERENCES "SurveillanceCorrectiveAction"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceActionEvidence" ADD CONSTRAINT "sr02_fk_052" FOREIGN KEY ("evidenceId") REFERENCES "SurveillanceEvidenceArtifact"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendOccurrence" ADD CONSTRAINT "sr02_fk_053" FOREIGN KEY ("trendIdentityId") REFERENCES "SurveillanceTrendIdentity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendOccurrence" ADD CONSTRAINT "sr02_fk_054" FOREIGN KEY ("sceneInstanceId") REFERENCES "SurveillanceSceneInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendOccurrence" ADD CONSTRAINT "sr02_fk_055" FOREIGN KEY ("criterionId") REFERENCES "SurveillanceCriterion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendOccurrence" ADD CONSTRAINT "sr02_fk_056" FOREIGN KEY ("candidateVarianceId") REFERENCES "SurveillanceCandidateVariance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SurveillanceTrendOccurrence" ADD CONSTRAINT "sr02_fk_057" FOREIGN KEY ("findingId") REFERENCES "SurveillanceReviewedFinding"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE UNIQUE INDEX "sr02_uqf_001" ON "SurveillanceBlueprint"("activeVersionId");
CREATE UNIQUE INDEX "sr02_uq_001" ON "SurveillanceBlueprint"("organizationId", "code");
CREATE INDEX "sr02_ix_001" ON "SurveillanceBlueprint"("organizationId", "sceneFamily", "status");
CREATE UNIQUE INDEX "sr02_uq_002" ON "SurveillanceBlueprintVersion"("organizationId", "blueprintId", "versionLabel");
CREATE INDEX "sr02_ix_002" ON "SurveillanceBlueprintVersion"("organizationId", "status", "effectiveFrom");
CREATE INDEX "sr02_ix_003" ON "SurveillanceApplicabilityProfile"("organizationId", "blueprintVersionId");
CREATE UNIQUE INDEX "sr02_uq_003" ON "SurveillanceSceneVariant"("organizationId", "blueprintVersionId", "code");
CREATE UNIQUE INDEX "sr02_uq_004" ON "SurveillanceReviewerPolicy"("organizationId", "blueprintVersionId", "code");
CREATE UNIQUE INDEX "sr02_uq_005" ON "SurveillanceReviewerAssignment"("organizationId", "userId");
CREATE INDEX "sr02_ix_004" ON "SurveillanceReviewerAssignment"("organizationId", "active");
CREATE UNIQUE INDEX "sr02_uq_006" ON "SurveillanceCriterion"("organizationId", "blueprintVersionId", "code");
CREATE UNIQUE INDEX "sr02_uq_007" ON "SurveillanceExpectedStateRule"("organizationId", "criterionId", "code");
CREATE UNIQUE INDEX "sr02_uq_008" ON "SurveillanceEvidenceRequirement"("organizationId", "criterionId", "code");
CREATE UNIQUE INDEX "sr02_uq_009" ON "SurveillanceCaptureStep"("organizationId", "blueprintVersionId", "sequence");
CREATE INDEX "sr02_ix_005" ON "SurveillanceAuthorityBinding"("organizationId", "criterionId");
CREATE INDEX "sr02_ix_006" ON "SurveillanceOrganizationRuleBinding"("organizationId", "criterionId");
CREATE UNIQUE INDEX "sr02_uqf_002" ON "SurveillanceTrendIdentity"("criterionId");
CREATE INDEX "sr02_ix_007" ON "SurveillanceTrendIdentity"("organizationId", "canonicalKey");
CREATE UNIQUE INDEX "sr02_uq_010" ON "SurveillanceRound"("organizationId", "roundKey");
CREATE INDEX "sr02_ix_008" ON "SurveillanceRound"("organizationId", "facilityProfileId", "startedAt");
CREATE INDEX "sr02_ix_009" ON "SurveillanceSceneInstance"("organizationId", "roundId");
CREATE UNIQUE INDEX "sr02_uqf_003" ON "SurveillanceApplicabilityResolution"("sceneInstanceId");
CREATE INDEX "sr02_ix_010" ON "SurveillanceApplicabilityResolution"("organizationId", "result");
CREATE UNIQUE INDEX "sr02_uq_011" ON "SurveillanceCriterionRuntime"("organizationId", "sceneInstanceId", "criterionId");
CREATE UNIQUE INDEX "sr02_uq_012" ON "SurveillanceEvidenceRequest"("organizationId", "sceneInstanceId", "evidenceRequirementId");
CREATE INDEX "sr02_ix_011" ON "SurveillanceEvidenceArtifact"("organizationId", "sceneInstanceId", "evidenceType");
CREATE UNIQUE INDEX "sr02_uq_013" ON "SurveillanceEvidenceDerivation"("organizationId", "parentEvidenceId", "derivedEvidenceId");
CREATE INDEX "sr02_ix_012" ON "SurveillanceEvidenceDerivation"("organizationId", "parentEvidenceId");
CREATE INDEX "sr02_ix_013" ON "SurveillanceEvidenceDerivation"("organizationId", "derivedEvidenceId");
CREATE INDEX "sr02_ix_014" ON "SurveillanceObservation"("organizationId", "sceneInstanceId", "criterionId");
CREATE INDEX "sr02_ix_015" ON "SurveillanceInterpretationDescriptor"("organizationId", "observationId");
CREATE INDEX "sr02_ix_016" ON "SurveillanceEvidenceAssessment"("organizationId", "sceneInstanceId", "criterionId", "createdAt");
CREATE INDEX "sr02_ix_017" ON "SurveillanceCandidateVariance"("organizationId", "sceneInstanceId", "status");
CREATE UNIQUE INDEX "sr02_uq_014" ON "SurveillanceReviewPacket"("organizationId", "candidateVarianceId", "packetVersion");
CREATE INDEX "sr02_ix_018" ON "SurveillanceDecisionRecord"("organizationId", "decisionType", "createdAt");
CREATE UNIQUE INDEX "sr02_uqf_004" ON "SurveillanceReviewedFinding"("candidateVarianceId");
CREATE UNIQUE INDEX "sr02_uqf_005" ON "SurveillanceReviewedFinding"("reviewPacketId");
CREATE INDEX "sr02_ix_019" ON "SurveillanceReviewedFinding"("organizationId", "status");
CREATE UNIQUE INDEX "sr02_uq_015" ON "SurveillanceFindingVersion"("organizationId", "findingId", "version");
CREATE UNIQUE INDEX "sr02_uq_016" ON "SurveillanceFindingCitation"("organizationId", "findingVersionId", "authorityBindingId");
CREATE INDEX "sr02_ix_020" ON "SurveillanceImmediateCorrection"("organizationId", "findingId");
CREATE INDEX "sr02_ix_021" ON "SurveillanceCorrectiveAction"("organizationId", "findingId", "status");
CREATE UNIQUE INDEX "sr02_uq_017" ON "SurveillanceActionEvidence"("organizationId", "actionId", "evidenceId");
CREATE INDEX "sr02_ix_022" ON "SurveillanceTrendOccurrence"("organizationId", "trendIdentityId", "eventTime");
