import { type WorkstreamStatuses } from "./workstreams.js";

/**
 * Overall case status. Values mirror prisma/schema.prisma enum CaseStatus — keep in sync.
 * OD-22 'RETURNED_FOR_MORE_INFORMATION' remains a Prisma-only known desync and is omitted here.
 */
export const LEGACY_CASE_STATUSES = [
  "CLINICAL_REVIEW",
  "LEGAL_REVIEW",
  "BENEFITS_REVIEW",
  "AUTHORIZATION_PREPARATION",
] as const;
export type LegacyCaseStatus = (typeof LEGACY_CASE_STATUSES)[number];

export const WRITABLE_CASE_STATUSES = [
  "DRAFT",
  "INTAKE_IN_PROGRESS",
  "DOCUMENTS_PENDING",
  "DOCUMENTS_RECEIVED",
  "EVIDENCE_PROCESSING",
  "EVIDENCE_REVIEW",
  "REVIEW_IN_PROGRESS",
  "INFORMATION_INCOMPLETE",
  "PACKET_PREPARATION",
  "READY_FOR_ROUTING",
  "ROUTING_IN_PROGRESS",
  "FACILITY_RESPONSE_PENDING",
  "ACCEPTED",
  "TRANSPORT_PENDING",
  "HANDOFF_IN_PROGRESS",
  "TRANSFER_COMPLETE",
  "CLOSED",
  "CANCELLED",
  "WITHDRAWN",
  "NO_PLACEMENT_FOUND",
  "REFERRED_TO_ALTERNATIVE_LEVEL",
  "MEDICAL_TRANSFER_REQUIRED",
] as const;
export type WritableCaseStatus = (typeof WRITABLE_CASE_STATUSES)[number];

export const CASE_STATUSES = [
  ...WRITABLE_CASE_STATUSES,
  ...LEGACY_CASE_STATUSES,
] as const;
export type CaseStatus = (typeof CASE_STATUSES)[number];

export const URGENCY_LEVELS = ["ROUTINE", "URGENT", "EMERGENT"] as const;
export type UrgencyLevel = (typeof URGENCY_LEVELS)[number];

const TERMINAL_SET = new Set(["CLOSED", "CANCELLED", "WITHDRAWN"]);

const WRITABLE_REOPEN_TARGETS = new Set<WritableCaseStatus>([
  "DRAFT",
  "INTAKE_IN_PROGRESS",
  "DOCUMENTS_PENDING",
  "DOCUMENTS_RECEIVED",
  "EVIDENCE_PROCESSING",
  "EVIDENCE_REVIEW",
  "REVIEW_IN_PROGRESS",
  "PACKET_PREPARATION",
  "READY_FOR_ROUTING",
  "ROUTING_IN_PROGRESS",
  "FACILITY_RESPONSE_PENDING",
  "ACCEPTED",
  "TRANSPORT_PENDING",
  "HANDOFF_IN_PROGRESS",
  "TRANSFER_COMPLETE"
]);

// Ratified 181-edge G2 Compatibility Transition Graph
const TRANSITIONS: Record<CaseStatus, Set<CaseStatus>> = {
  DRAFT: new Set(["INTAKE_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  INTAKE_IN_PROGRESS: new Set(["DRAFT", "DOCUMENTS_PENDING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  DOCUMENTS_PENDING: new Set(["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_RECEIVED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  DOCUMENTS_RECEIVED: new Set(["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "EVIDENCE_PROCESSING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  EVIDENCE_PROCESSING: new Set(["INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_REVIEW", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  EVIDENCE_REVIEW: new Set(["DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  REVIEW_IN_PROGRESS: new Set(["DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED", "PACKET_PREPARATION"]),
  PACKET_PREPARATION: new Set(["REVIEW_IN_PROGRESS", "READY_FOR_ROUTING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  READY_FOR_ROUTING: new Set(["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "ROUTING_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  ROUTING_IN_PROGRESS: new Set(["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "FACILITY_RESPONSE_PENDING", "CANCELLED", "WITHDRAWN", "NO_PLACEMENT_FOUND", "REFERRED_TO_ALTERNATIVE_LEVEL", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  FACILITY_RESPONSE_PENDING: new Set(["PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "ACCEPTED", "CANCELLED", "WITHDRAWN", "NO_PLACEMENT_FOUND", "REFERRED_TO_ALTERNATIVE_LEVEL", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  ACCEPTED: new Set(["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "TRANSPORT_PENDING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  TRANSPORT_PENDING: new Set(["ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "HANDOFF_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  HANDOFF_IN_PROGRESS: new Set(["FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "TRANSFER_COMPLETE", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  TRANSFER_COMPLETE: new Set(["ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  CLOSED: new Set(),
  INFORMATION_INCOMPLETE: new Set(["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "TRANSFER_COMPLETE", "CLOSED", "CANCELLED", "WITHDRAWN"]),
  NO_PLACEMENT_FOUND: new Set(["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  REFERRED_TO_ALTERNATIVE_LEVEL: new Set(["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  MEDICAL_TRANSFER_REQUIRED: new Set(["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "TRANSFER_COMPLETE", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"]),
  CLINICAL_REVIEW: new Set(["DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  LEGAL_REVIEW: new Set(["EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  BENEFITS_REVIEW: new Set(["EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  AUTHORIZATION_PREPARATION: new Set(["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"]),
  CANCELLED: new Set(),
  WITHDRAWN: new Set()
};

export function canTransitionCase(from: CaseStatus, to: CaseStatus): boolean {
  if (from === to) return false;
  return TRANSITIONS[from]?.has(to) ?? false;
}

export interface ClarityCase {
  caseKey: string;
  organizationId: string;
  status: CaseStatus;
  urgency: UrgencyLevel;
  workstreams: WorkstreamStatuses;
}

/**
 * Reopening is NOT a normal transition: canTransitionCase deliberately
 * rejects everything out of a terminal state. Reopen is an explicitly
 * permitted, role-gated, rationale-required exception path handled by the
 * command service. It may only land on an active (non-terminal,
 * non-exception) writable state.
 */
export function canReopenCase(from: CaseStatus, to: CaseStatus): boolean {
  return TERMINAL_SET.has(from) && WRITABLE_REOPEN_TARGETS.has(to as WritableCaseStatus);
}

export function transitionCase(c: ClarityCase, to: CaseStatus): ClarityCase {
  if (!canTransitionCase(c.status, to)) {
    throw new Error(`Invalid case transition: ${c.status} -> ${to}`);
  }
  return { ...c, status: to };
}

/**
 * Emergency and fairness rule (MASTER_ARCHITECTURE §8; MASTER_BUILD_PROMPT rule 10):
 * clinical review of an emergent case proceeds regardless of financial workstreams.
 * Only clinically relevant blockers may hold emergency clinical review.
 */
export function canBeginClinicalReview(c: ClarityCase): boolean {
  if (c.urgency === "EMERGENT") {
    // benefits/authorization/placement state is irrelevant to emergency clinical review
    return c.workstreams.clinical !== "NOT_APPLICABLE";
  }
  return c.workstreams.clinical === "READY" || c.workstreams.clinical === "IN_PROGRESS"
    || c.workstreams.clinical === "NOT_STARTED";
}
