import type { AppState, CustodyLedgerEvent } from "./types";
import { sealLedgerEvents, sha256 } from "./custodyLedger";
import { LOUISIANA_EPEC_RULE_SET } from "./epecRuleSets";

const now = "2026-07-08T15:00:00.000Z";
const epecRuleSetId = LOUISIANA_EPEC_RULE_SET.id;

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60000).toISOString();
}

export async function createSeedState(): Promise<AppState> {
  const packetHash = await sha256("packet-ready-case-demo");
  const pecSealHash = await sha256("pec-seal-case-004-demo");

  // Each case's custody-ledger events are sealed into their own independent hash chain (mirrors
  // custodyLedger.ts's runtime appendCustodyLedgerEvent, which also chains per case) so that
  // filtering state.custodyLedgerEvents down to a single caseId still yields a chain whose first
  // event has previousHash === null and verifies cleanly in the Custody Ledger workspace.
  const case004RawEvents: Array<Omit<CustodyLedgerEvent, "eventHash" | "previousHash">> = [
    {
      id: "ledger-001",
      caseId: "case-004",
      eventType: "CASE_CREATED",
      actor: "Intake Coordinator",
      occurredAt: "2026-07-08T14:02:00.000Z",
      payload: { stage: "Referral", source: "Family call" },
    },
    {
      id: "ledger-001b",
      caseId: "case-004",
      eventType: "OPC_ISSUED",
      actor: "Crisis Line Dispatcher",
      occurredAt: "2026-07-08T14:05:00.000Z",
      payload: { statuteRef: LOUISIANA_EPEC_RULE_SET.statuteRefs.opc, grounds: ["Gravely disabled", "Dangerous to self"], containsPhi: false },
    },
    {
      id: "ledger-001c",
      caseId: "case-004",
      eventType: "PEC_EXECUTED",
      actor: "Dr. A. Fontenot",
      occurredAt: "2026-07-08T14:12:00.000Z",
      payload: { statuteRef: LOUISIANA_EPEC_RULE_SET.statuteRefs.pec, findings: ["Gravely disabled", "Dangerous to self"], sealHash: pecSealHash, containsPhi: false },
    },
    {
      id: "ledger-002",
      caseId: "case-004",
      eventType: "LEGAL_DRAFT_CREATED",
      actor: "Lead Clinician",
      occurredAt: "2026-07-08T14:18:00.000Z",
      payload: { legalStatus: "PEC", reviewStatus: "Counsel validation required" },
    },
    {
      id: "ledger-003",
      caseId: "case-004",
      eventType: "PACKET_HASH_SEALED",
      actor: "Intake Coordinator",
      occurredAt: "2026-07-08T14:31:00.000Z",
      payload: { packetHash, completeness: 94 },
    },
    {
      id: "ledger-004",
      caseId: "case-004",
      eventType: "FACILITY_RESPONSE_RECEIVED",
      actor: "Mock Receiving Facility",
      occurredAt: "2026-07-08T14:45:00.000Z",
      payload: { response: "Accept", receipt: "mock-acceptance-receipt" },
    },
  ];

  const case001RawEvents: Array<Omit<CustodyLedgerEvent, "eventHash" | "previousHash">> = [
    {
      id: "ledger-005",
      caseId: "case-001",
      eventType: "OPC_ISSUED",
      actor: "Ofc. R. Guidry, LPD",
      occurredAt: "2026-07-08T13:10:00.000Z",
      payload: { statuteRef: LOUISIANA_EPEC_RULE_SET.statuteRefs.opc, grounds: ["Dangerous to self"], containsPhi: false },
    },
  ];

  return {
    cases: [
      {
        id: "case-001",
        patientToken: { id: "pt-001", displayName: "Adult Demo A", ageBand: "Adult", location: "ED bay 4" },
        currentStage: "Assessment",
        priority: "Emergent",
        openedAt: "2026-07-08T13:05:00.000Z",
        assignedOwner: "Lead Intake Clinician",
        legalStatus: "PEC",
        packetCompleteness: 62,
        routingStatus: "Draft",
      },
      {
        id: "case-002",
        patientToken: { id: "pt-002", displayName: "Geriatric Demo B", ageBand: "Geriatric", location: "Medical ED" },
        currentStage: "Intake",
        priority: "Urgent",
        openedAt: "2026-07-08T13:30:00.000Z",
        assignedOwner: "Mobile Crisis Clinician",
        legalStatus: "Unknown",
        packetCompleteness: 41,
        routingStatus: "Draft",
      },
      {
        id: "case-003",
        patientToken: { id: "pt-003", displayName: "Youth Demo C", ageBand: "Youth", location: "School counselor office" },
        currentStage: "Intake",
        priority: "Urgent",
        openedAt: "2026-07-08T13:45:00.000Z",
        assignedOwner: "Intake Coordinator",
        legalStatus: "Unknown",
        packetCompleteness: 38,
        routingStatus: "Draft",
      },
      {
        id: "case-004",
        patientToken: { id: "pt-004", displayName: "Packet Ready Demo D", ageBand: "Adult", location: "Crisis stabilization unit" },
        currentStage: "Routing",
        priority: "Emergent",
        openedAt: "2026-07-08T14:02:00.000Z",
        assignedOwner: "Lead Intake Clinician",
        legalStatus: "PEC",
        packetCompleteness: 94,
        routingStatus: "Accepted",
      },
    ],
    encounters: [
      { id: "enc-001", caseId: "case-001", mode: "Clinical", startedAt: now, referralSource: "Family call", insuranceStatus: "Pending verification" },
      { id: "enc-002", caseId: "case-002", mode: "Clinical", startedAt: now, referralSource: "ED physician", insuranceStatus: "Unknown" },
      { id: "enc-003", caseId: "case-003", mode: "Field", startedAt: now, referralSource: "School counselor", insuranceStatus: "Not provided" },
      { id: "enc-004", caseId: "case-004", mode: "Clinical", startedAt: now, referralSource: "Crisis line", insuranceStatus: "Verified" },
    ],
    assessments: [
      {
        id: "assess-001",
        caseId: "case-001",
        mode: "Clinical",
        presentingProblem: "Family reports suicidal statements and recent access to medication supply.",
        precipitatingEvents: "Argument with sibling and worsening isolation reported.",
        dangerToSelf: "Suicidal statements and possible medication access.",
        dangerToOthers: "Not assessed",
        graveDisability: "Unknown",
        orientation: "Oriented",
        psychosis: "No measurements found",
        moodSleepAppetite: "Poor sleep; appetite unknown.",
        psychiatricHistory: "Unknown",
        treatmentHistory: "Unknown",
        substanceUse: "Not assessed",
        medicalConcerns: "Unknown",
        environmentalStressors: "Family conflict reported.",
        collateralContacts: "Sibling phone collateral partial.",
        protectiveFactors: "Not assessed",
        lowerLevelConsidered: "Unknown",
        mentalStatus: "Tearful, poor sleep, guarded, oriented.",
        collateralStatus: "Partial",
        formulation: "",
        reviewStatus: "Draft",
      },
      {
        id: "assess-002",
        caseId: "case-002",
        mode: "Clinical",
        presentingProblem: "Abrupt confusion and disoriented behavior reported after medication changes.",
        precipitatingEvents: "Abrupt confusion after medication changes.",
        dangerToSelf: "Unknown",
        dangerToOthers: "Unknown",
        graveDisability: "Needs assessment of ADL/IADL change.",
        orientation: "Disoriented to date.",
        psychosis: "Not assessed",
        moodSleepAppetite: "Worried affect; sleep/appetite unknown.",
        psychiatricHistory: "Unknown",
        treatmentHistory: "Medication changes reported; details missing.",
        substanceUse: "Not assessed",
        medicalConcerns: "Possible delirium or medical instability.",
        environmentalStressors: "Unknown",
        collateralContacts: "ED staff collateral partial.",
        protectiveFactors: "Not assessed",
        lowerLevelConsidered: "Medical differential required before psychiatric-only framing.",
        mentalStatus: "Fluctuating attention, disoriented to date, worried affect.",
        collateralStatus: "Partial",
        formulation: "Needs delirium and baseline cognition review before psychiatric-only framing.",
        reviewStatus: "Draft",
      },
      {
        id: "assess-003",
        caseId: "case-003",
        mode: "Field",
        presentingProblem: "Youth disclosed self-harm thoughts to school counselor.",
        precipitatingEvents: "School counselor referral after self-harm disclosure.",
        dangerToSelf: "Self-harm disclosure; details missing.",
        dangerToOthers: "Not assessed",
        graveDisability: "Unknown",
        orientation: "Oriented by field report.",
        psychosis: "Not assessed",
        moodSleepAppetite: "Withdrawn and anxious; sleep/appetite unknown.",
        psychiatricHistory: "Unknown",
        treatmentHistory: "Unknown",
        substanceUse: "Not assessed",
        medicalConcerns: "Unknown",
        environmentalStressors: "School stressor context incomplete.",
        collateralContacts: "Guardian not yet reached.",
        protectiveFactors: "School counselor engaged.",
        lowerLevelConsidered: "Unknown pending guardian collateral.",
        mentalStatus: "Withdrawn, quiet, anxious.",
        collateralStatus: "Missing",
        formulation: "Initial field capture requires guardian collateral and means-restriction documentation.",
        reviewStatus: "Draft",
      },
      {
        id: "assess-004",
        caseId: "case-004",
        mode: "Clinical",
        presentingProblem: "Crisis line referral with escalating paranoia and unsafe behavior.",
        precipitatingEvents: "Three nights of insomnia and escalating paranoia.",
        dangerToSelf: "Unsafe behavior under review.",
        dangerToOthers: "No direct threat documented.",
        graveDisability: "Poor sleep and paranoia impair safe routine.",
        orientation: "Oriented with impaired judgment.",
        psychosis: "Paranoia documented by collateral.",
        moodSleepAppetite: "Severe insomnia; appetite unknown.",
        psychiatricHistory: "Prior outpatient treatment reported.",
        treatmentHistory: "Crisis stabilization attempted; medication reconciliation pending.",
        substanceUse: "No measurements found",
        medicalConcerns: "Medication reconciliation pending.",
        environmentalStressors: "Family reports unsafe pacing at home.",
        collateralContacts: "Mother collateral documented.",
        protectiveFactors: "Family engaged and transfer packet available.",
        lowerLevelConsidered: "Crisis stabilization attempted; higher structure under clinician review.",
        mentalStatus: "Paranoid, pressured speech, impaired judgment.",
        collateralStatus: "Documented",
        formulation: "Available facts support clinician review for 24-hour structured care and transfer packet routing.",
        reviewStatus: "Needs clinician review",
      },
    ],
    sourceReferences: [
      { id: "src-001", caseId: "case-001", type: "Family collateral", label: "Sibling phone call", excerpt: "Stated patient said they did not want to wake up and had pills nearby.", confidence: "Medium" },
      { id: "src-002", caseId: "case-002", type: "Clinician observation", label: "ED observation", excerpt: "Fluctuating attention and abrupt confusion noted during intake.", confidence: "High" },
      { id: "src-003", caseId: "case-003", type: "Referral document", label: "School referral note", excerpt: "Counselor reports self-harm disclosure; guardian not yet reached.", confidence: "Needs verification" },
      { id: "src-004", caseId: "case-004", type: "Family collateral", label: "Mother collateral", excerpt: "Reported unsafe pacing, paranoia, and inability to sleep for three nights.", confidence: "High" },
    ],
    riskFindings: [
      { id: "risk-001", caseId: "case-001", type: "Danger to self", summary: "Recent suicidal statements with possible medication access.", sourceReferenceIds: ["src-001"], severity: "High", reviewStatus: "Draft" },
      { id: "risk-002", caseId: "case-002", type: "Medical instability", summary: "Abrupt confusion requires medical differential before psychiatric-only disposition.", sourceReferenceIds: ["src-002"], severity: "Moderate", reviewStatus: "Draft" },
      { id: "risk-003", caseId: "case-003", type: "Danger to self", summary: "Youth disclosed self-harm thoughts; guardian collateral pending.", sourceReferenceIds: ["src-003"], severity: "Moderate", reviewStatus: "Draft" },
      { id: "risk-004", caseId: "case-004", type: "Grave disability", summary: "Paranoia and poor sleep impair safe functioning.", sourceReferenceIds: ["src-004"], severity: "High", reviewStatus: "Needs clinician review" },
    ],
    medicalNecessitySnapshots: [
      {
        id: "mn-001",
        caseId: "case-001",
        severityEvidence: ["Suicidal statements", "Potential access to medication"],
        functionalImpairment: ["Poor sleep", "Family reports impaired safety"],
        lowerLevelConsidered: "Unknown",
        missingItems: ["Full risk formulation", "Means details", "Protective factors"],
        draftNarrative: "Available facts support clinician review for structured safety monitoring. Draft only.",
        reviewStatus: "Needs clinician review",
      },
      {
        id: "mn-004",
        caseId: "case-004",
        severityEvidence: ["Escalating paranoia", "Unsafe behavior", "Severe insomnia"],
        functionalImpairment: ["Unable to maintain safe routine", "Needs supervised transfer"],
        lowerLevelConsidered: "Crisis stabilization attempted; higher structure under review.",
        missingItems: ["Receiving facility medication reconciliation"],
        draftNarrative: "Documentation indicates risk and impairment for clinician review. This is not a final level-of-care determination.",
        reviewStatus: "Needs clinician review",
      },
    ],
    legalInstruments: [
      {
        id: "legal-001",
        caseId: "case-001",
        legalStatus: "OPC",
        requiredFactsComplete: true,
        clockStatus: "Active",
        draftText: "Draft OPC scaffold. Louisiana statutory language and timing require counsel validation.",
        reviewStatus: "Counsel validation required",
        ruleSetId: epecRuleSetId,
        opc: {
          issuedAt: "2026-07-08T13:10:00.000Z",
          requestor: "Ofc. R. Guidry, LPD",
          relation: "Responding officer — welfare check",
          observed: "Subject on the ED loading dock stating intent to harm self; family reports four days of worsening isolation and refusal to eat.",
          grounds: ["Dangerous to self"],
          expiresAt: "2026-07-11T13:10:00.000Z",
        },
      },
      {
        id: "legal-004",
        caseId: "case-004",
        legalStatus: "PEC",
        requiredFactsComplete: true,
        clockStatus: "Active",
        draftText: "Draft PEC packet scaffold bound to source references and packet hash. Counsel validation required.",
        reviewStatus: "Counsel validation required",
        ruleSetId: epecRuleSetId,
        opc: {
          issuedAt: "2026-07-08T14:05:00.000Z",
          requestor: "Crisis Line Dispatcher",
          relation: "Crisis line intake",
          observed: "Caller (mother) reported unsafe pacing, escalating paranoia, and inability to sleep for three nights; patient refused voluntary transport when offered.",
          grounds: ["Gravely disabled", "Dangerous to self"],
          expiresAt: "2026-07-11T14:05:00.000Z",
        },
        pec: {
          examinerName: "Dr. A. Fontenot",
          examinerType: "Physician (MD/DO)",
          examinedAt: "2026-07-08T14:10:00.000Z",
          findings: ["Gravely disabled", "Dangerous to self"],
          conditions: ["Unwilling to seek voluntary admission"],
          telemedicine: false,
          narrative: "Pt presents with escalating paranoia, pressured speech, and impaired judgment; unable to maintain safe routine per collateral. Refuses voluntary admission; requires inpatient stabilization.",
          executedAt: "2026-07-08T14:12:00.000Z",
          sealHash: pecSealHash,
          transmittedAt: "2026-07-08T14:45:00.000Z",
          facilityResponseId: "resp-004-a",
        },
      },
    ],
    custodyLedgerEvents: [...(await sealLedgerEvents(case004RawEvents)), ...(await sealLedgerEvents(case001RawEvents))],
    referralPackets: [
      {
        id: "packet-004",
        caseId: "case-004",
        status: "Sent",
        completeness: 94,
        includedArtifactLabels: ["Assessment summary", "Risk findings", "Medical necessity draft", "Legal draft", "Source references"],
        packetHash,
      },
    ],
    facilityReferrals: [
      { id: "ref-004-a", caseId: "case-004", packetId: "packet-004", facilityName: "Bayou Vista Behavioral", status: "Accepted", sentAt: "2026-07-08T14:36:00.000Z" },
      { id: "ref-004-b", caseId: "case-004", packetId: "packet-004", facilityName: "Cypress Recovery Hospital", status: "Declined", sentAt: "2026-07-08T14:36:00.000Z" },
    ],
    facilityResponses: [
      { id: "resp-004-a", referralId: "ref-004-a", response: "Accept", reasonCode: "accepted_packet_complete", note: "Accepted pending arrival and nurse handoff.", respondedAt: "2026-07-08T14:45:00.000Z" },
      { id: "resp-004-b", referralId: "ref-004-b", response: "Decline", reasonCode: "acuity_too_high", note: "Declined due to current unit acuity mix.", respondedAt: "2026-07-08T14:47:00.000Z" },
    ],
    complianceClocks: [
      { id: "clock-001", caseId: "case-001", label: "Insurance verification (parallel lane)", lane: "Financial", startedAt: minutesAgo(35), targetMinutes: 120, counselValidationRequired: false },
      { id: "clock-002", caseId: "case-001", label: "PEC review window (configurable demo value)", lane: "Legal", startedAt: minutesAgo(60), targetMinutes: 720, counselValidationRequired: true },
      { id: "clock-003", caseId: "case-002", label: "Referral to screening", lane: "Clinical", startedAt: minutesAgo(50), targetMinutes: 60, counselValidationRequired: false },
      { id: "clock-004", caseId: "case-003", label: "Referral to screening", lane: "Clinical", startedAt: minutesAgo(95), targetMinutes: 60, counselValidationRequired: false },
      { id: "clock-005", caseId: "case-004", label: "Disposition to transport", lane: "Clinical", startedAt: minutesAgo(20), targetMinutes: 240, counselValidationRequired: false },
      { id: "opc-case-001", caseId: "case-001", label: `OPC transport window (${LOUISIANA_EPEC_RULE_SET.statuteRefs.opc})`, lane: "Legal", startedAt: minutesAgo(40), targetMinutes: LOUISIANA_EPEC_RULE_SET.windowsMinutes.opc, counselValidationRequired: true },
      { id: "cec-case-004", caseId: "case-004", label: `CEC review window (${LOUISIANA_EPEC_RULE_SET.statuteRefs.cec})`, lane: "Legal", startedAt: minutesAgo(15), targetMinutes: LOUISIANA_EPEC_RULE_SET.windowsMinutes.cec, counselValidationRequired: true },
    ],
    units: [
      { id: "unit-a", name: "Adult Unit A", population: "Adult", acuityCeiling: 3.5 },
      { id: "unit-b", name: "Geriatric Unit B", population: "Geriatric", acuityCeiling: 3 },
    ],
    beds: [
      { id: "bed-101a", unitId: "unit-a", room: "Room 101", label: "101-A", nearNurseStation: true, nearExit: false, status: "Occupied", occupantToken: "occ-101a", occupantAcuity: { acuityLevel: 3, aggressionRisk: "Low", elopementRisk: "Low", siPrecautions: true, vulnerableAdult: false, observationLevel: "Q15" } },
      { id: "bed-101b", unitId: "unit-a", room: "Room 101", label: "101-B", nearNurseStation: true, nearExit: false, status: "Occupied", occupantToken: "occ-101b", occupantAcuity: { acuityLevel: 2, aggressionRisk: "Low", elopementRisk: "Low", siPrecautions: false, vulnerableAdult: false, observationLevel: "Routine" } },
      { id: "bed-102a", unitId: "unit-a", room: "Room 102", label: "102-A", nearNurseStation: false, nearExit: false, status: "Occupied", occupantToken: "occ-102a", occupantAcuity: { acuityLevel: 4, aggressionRisk: "High", elopementRisk: "Low", siPrecautions: false, vulnerableAdult: false, observationLevel: "1:1" } },
      { id: "bed-102b", unitId: "unit-a", room: "Room 102", label: "102-B", nearNurseStation: false, nearExit: false, status: "Available" },
      { id: "bed-103a", unitId: "unit-a", room: "Room 103", label: "103-A", nearNurseStation: false, nearExit: true, status: "Blocked" },
      { id: "bed-103b", unitId: "unit-a", room: "Room 103", label: "103-B", nearNurseStation: false, nearExit: true, status: "Available" },
      { id: "bed-201a", unitId: "unit-b", room: "Room 201", label: "201-A", nearNurseStation: true, nearExit: false, status: "Occupied", occupantToken: "occ-201a", occupantAcuity: { acuityLevel: 2, aggressionRisk: "Low", elopementRisk: "Moderate", siPrecautions: false, vulnerableAdult: true, observationLevel: "Q15" } },
      { id: "bed-201b", unitId: "unit-b", room: "Room 201", label: "201-B", nearNurseStation: true, nearExit: false, status: "Available" },
    ],
    placementRecommendations: [
      {
        id: "rec-004",
        caseId: "case-004",
        bedId: "bed-102b",
        candidateAcuity: { acuityLevel: 4, aggressionRisk: "Moderate", elopementRisk: "High", siPrecautions: false, vulnerableAdult: false, observationLevel: "Q15" },
        rationale: "Only open adult bed with same-day availability after acceptance by Bayou Vista Behavioral.",
        status: "Suggested",
      },
    ],
    auditLogs: [
      { id: "audit-001", caseId: "case-004", action: "Seed packet sent", actor: "System demo seed", occurredAt: "2026-07-08T14:36:00.000Z" },
    ],
    analyticsEvents: [
      {
        id: "analytics-001",
        source: "clarity-v0.1",
        eventType: "ROUTING_RESPONSE_RECEIVED",
        occurredAt: "2026-07-08T14:45:00.000Z",
        organizationToken: "demo-org",
        caseId: "case-004",
        metricsSafePayload: { response: "Accept", packetCompleteness: 94, containsPhi: false },
      },
    ],
  };
}
