import { createHash } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import type { DocumentStorage, StoredDocument } from "@clarity/domain-contracts";

/** Thrown when a storage key has no stored bytes (should not happen for keys the service itself issued). */
export class StoredDocumentNotFoundError extends Error {
  constructor(storageKey: string) {
    super(`No stored bytes for storage key "${storageKey}"`);
    this.name = "StoredDocumentNotFoundError";
  }
}

/** Thrown when a storage key is not one this adapter could have issued. */
export class InvalidStorageKeyError extends Error {
  constructor(storageKey: string) {
    super(`Storage key "${storageKey}" is not a valid key for this adapter`);
    this.name = "InvalidStorageKeyError";
  }
}

/**
 * Keys are opaque and generated by the adapter itself: `${caseId}/${sha256}`,
 * where caseId is an internally generated id and sha256 is derived from the
 * bytes. No caller-supplied filename or path ever becomes part of a key.
 * Both segments must match a strict allowlist — anything else (.., slashes,
 * absolute paths, control characters) is rejected before touching storage.
 */
const KEY_SEGMENT = /^[A-Za-z0-9_-]{1,128}$/;
const SHA256_HEX = /^[a-f0-9]{64}$/;

function assertValidKey(storageKey: string): { caseSegment: string; hashSegment: string } {
  const parts = storageKey.split("/");
  if (parts.length !== 2) throw new InvalidStorageKeyError(storageKey);
  const [caseSegment, hashSegment] = parts as [string, string];
  if (!KEY_SEGMENT.test(caseSegment) || !SHA256_HEX.test(hashSegment)) {
    throw new InvalidStorageKeyError(storageKey);
  }
  return { caseSegment, hashSegment };
}

function keyFor(caseId: string, content: Uint8Array): StoredDocument {
  if (!KEY_SEGMENT.test(caseId)) throw new InvalidStorageKeyError(caseId);
  const sha256 = createHash("sha256").update(content).digest("hex");
  return { storageKey: `${caseId}/${sha256}`, sha256, size: content.byteLength };
}

/**
 * Synthetic, in-memory, content-addressed document storage — for tests and
 * as the default when no filesystem root is configured. Content-addressing
 * makes re-storing identical bytes an idempotent overwrite.
 */
export class InMemoryDocumentStorage implements DocumentStorage {
  #blobs = new Map<string, Uint8Array>();

  async put(caseId: string, content: Uint8Array): Promise<StoredDocument> {
    const stored = keyFor(caseId, content);
    this.#blobs.set(stored.storageKey, content);
    return stored;
  }

  async get(storageKey: string): Promise<Uint8Array> {
    assertValidKey(storageKey);
    const blob = this.#blobs.get(storageKey);
    if (!blob) throw new StoredDocumentNotFoundError(storageKey);
    return blob;
  }

  async delete(storageKey: string): Promise<void> {
    assertValidKey(storageKey);
    this.#blobs.delete(storageKey); // idempotent
  }

  async exists(storageKey: string): Promise<boolean> {
    assertValidKey(storageKey);
    return this.#blobs.has(storageKey);
  }
}

/**
 * Local development filesystem adapter (ADR-0007). DEVELOPMENT ONLY — not a
 * production object store: no durability guarantees, no encryption at rest,
 * no access controls beyond filesystem permissions, and it must never hold
 * anything but synthetic content. The root directory defaults to
 * `.local-object-storage/` (git-ignored) and every path is resolved and
 * verified to stay under the root, so neither a hostile storage key nor a
 * hostile filename can escape it. No public URLs exist; bytes are reachable
 * only through this adapter behind the command service's authorization.
 */
export class LocalFilesystemObjectStorage implements DocumentStorage {
  constructor(private readonly rootDir: string = path.resolve(".local-object-storage")) {}

  private resolveKey(storageKey: string): string {
    const { caseSegment, hashSegment } = assertValidKey(storageKey);
    const abs = path.resolve(this.rootDir, caseSegment, hashSegment);
    if (!abs.startsWith(path.resolve(this.rootDir) + path.sep)) {
      throw new InvalidStorageKeyError(storageKey);
    }
    return abs;
  }

  async put(caseId: string, content: Uint8Array): Promise<StoredDocument> {
    const stored = keyFor(caseId, content);
    const abs = this.resolveKey(stored.storageKey);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, content);
    return stored;
  }

  async get(storageKey: string): Promise<Uint8Array> {
    const abs = this.resolveKey(storageKey);
    try {
      return new Uint8Array(await readFile(abs));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") {
        throw new StoredDocumentNotFoundError(storageKey);
      }
      throw e;
    }
  }

  async delete(storageKey: string): Promise<void> {
    const abs = this.resolveKey(storageKey);
    await rm(abs, { force: true }); // idempotent
  }

  async exists(storageKey: string): Promise<boolean> {
    const abs = this.resolveKey(storageKey);
    try {
      await stat(abs);
      return true;
    } catch {
      return false;
    }
  }
}
