import { describe, expect, it } from "vitest";
import { CASE_STATUSES, canTransitionCase } from "@clarity/domain-contracts";

// Ratified 181-edge G2 Compatibility Transition Graph Adjacency Set
const EXPECTED_G2_ADJACENCY: Record<string, string[]> = {
  DRAFT: ["INTAKE_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  INTAKE_IN_PROGRESS: ["DRAFT", "DOCUMENTS_PENDING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  DOCUMENTS_PENDING: ["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_RECEIVED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  DOCUMENTS_RECEIVED: ["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "EVIDENCE_PROCESSING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  EVIDENCE_PROCESSING: ["INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_REVIEW", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  EVIDENCE_REVIEW: ["DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  REVIEW_IN_PROGRESS: ["DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED", "PACKET_PREPARATION"],
  PACKET_PREPARATION: ["REVIEW_IN_PROGRESS", "READY_FOR_ROUTING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  READY_FOR_ROUTING: ["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "ROUTING_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  ROUTING_IN_PROGRESS: ["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "FACILITY_RESPONSE_PENDING", "CANCELLED", "WITHDRAWN", "NO_PLACEMENT_FOUND", "REFERRED_TO_ALTERNATIVE_LEVEL", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  FACILITY_RESPONSE_PENDING: ["PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "ACCEPTED", "CANCELLED", "WITHDRAWN", "NO_PLACEMENT_FOUND", "REFERRED_TO_ALTERNATIVE_LEVEL", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  ACCEPTED: ["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "TRANSPORT_PENDING", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  TRANSPORT_PENDING: ["ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "HANDOFF_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  HANDOFF_IN_PROGRESS: ["FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "TRANSFER_COMPLETE", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  TRANSFER_COMPLETE: ["ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  CLOSED: [],
  INFORMATION_INCOMPLETE: ["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "TRANSFER_COMPLETE", "CLOSED", "CANCELLED", "WITHDRAWN"],
  NO_PLACEMENT_FOUND: ["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  REFERRED_TO_ALTERNATIVE_LEVEL: ["READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  MEDICAL_TRANSFER_REQUIRED: ["DRAFT", "INTAKE_IN_PROGRESS", "DOCUMENTS_PENDING", "DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "READY_FOR_ROUTING", "ROUTING_IN_PROGRESS", "FACILITY_RESPONSE_PENDING", "ACCEPTED", "TRANSPORT_PENDING", "HANDOFF_IN_PROGRESS", "TRANSFER_COMPLETE", "CLOSED", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE"],
  CLINICAL_REVIEW: ["DOCUMENTS_RECEIVED", "EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  LEGAL_REVIEW: ["EVIDENCE_PROCESSING", "EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  BENEFITS_REVIEW: ["EVIDENCE_REVIEW", "REVIEW_IN_PROGRESS", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  AUTHORIZATION_PREPARATION: ["REVIEW_IN_PROGRESS", "PACKET_PREPARATION", "CANCELLED", "WITHDRAWN", "INFORMATION_INCOMPLETE", "MEDICAL_TRANSFER_REQUIRED"],
  CANCELLED: [],
  WITHDRAWN: []
};

describe("G2 Semantic State Graph Matrix", () => {
  it("matches the ratified 181-edge G2 compatibility graph exactly", () => {
    let edgeCount = 0;
    const unexpectedAdditions: string[] = [];
    const unexpectedOmissions: string[] = [];

    for (const from of CASE_STATUSES) {
      for (const to of CASE_STATUSES) {
        const allowed = canTransitionCase(from, to);
        const expected = EXPECTED_G2_ADJACENCY[from]?.includes(to) ?? false;

        if (allowed) edgeCount++;

        if (allowed && !expected) {
          unexpectedAdditions.push(`${from} -> ${to}`);
        } else if (!allowed && expected) {
          unexpectedOmissions.push(`${from} -> ${to}`);
        }
      }
    }

    expect(unexpectedAdditions).toEqual([]);
    expect(unexpectedOmissions).toEqual([]);
    expect(edgeCount).toBe(181);
  });
});
